---
title: "R for Bioinformatics"
author: "Amy Yarnell"
title-block-banner: white
title-block-banner-color: black
navbar:
    page-navigation: true
format: 
  html:
    embed-resources: true
toc: true
editor: source
css: styles.scss
---

## Course Description: 

This hands-on workshop is designed for researchers who are already familiar with R and the tidyverse and want to explore how R can be used for common bioinformatics tasks. We’ll introduce tools and workflows for working with biological sequence data—such as retrieving DNA sequences, aligning them, and building phylogenetic trees—using packages from the Bioconductor project. Whether you’re working with genomics, transcriptomics, or other biological datasets, this session will help you get started with the bioinformatics capabilities of R.

After this session, participants will be able to:

- Work with biological data in R using specialized packages
- Explore and manipulate common types of bioinformatics data
- Apply tidyverse skills to bioinformatics workflows
- Become familiar with widely used bioinformatics packages and how to find them



## Acknowledgements
Many thanks to Jean-Paul Courneya for thoughtful feedback and testing that helped shaped this lesson

## License
This work is licensed under a [Creative Commons Attribution 4.0 International License (CC BY)](https://creativecommons.org/licenses/by-sa/4.0/)